#!/bin/bash
sbatch ./exps/ElasticNet_3_5.sh
sbatch ./exps/ElasticNet_3_10.sh
sbatch ./exps/ElasticNet_3_15.sh
sbatch ./exps/ElasticNet_5_5.sh
sbatch ./exps/ElasticNet_5_10.sh
sbatch ./exps/ElasticNet_5_15.sh
sbatch ./exps/ElasticNet_7_5.sh
sbatch ./exps/ElasticNet_7_10.sh
sbatch ./exps/ElasticNet_7_15.sh
sbatch ./exps/Lars_3_5.sh
sbatch ./exps/Lars_3_10.sh
sbatch ./exps/Lars_3_15.sh
sbatch ./exps/Lars_5_5.sh
sbatch ./exps/Lars_5_10.sh
sbatch ./exps/Lars_5_15.sh
sbatch ./exps/Lars_7_5.sh
sbatch ./exps/Lars_7_10.sh
sbatch ./exps/Lars_7_15.sh
sbatch ./exps/Lasso_3_5.sh
sbatch ./exps/Lasso_3_10.sh
sbatch ./exps/Lasso_3_15.sh
sbatch ./exps/Lasso_5_5.sh
sbatch ./exps/Lasso_5_10.sh
sbatch ./exps/Lasso_5_15.sh
sbatch ./exps/Lasso_7_5.sh
sbatch ./exps/Lasso_7_10.sh
sbatch ./exps/Lasso_7_15.sh
sbatch ./exps/LassoLars_3_5.sh
sbatch ./exps/LassoLars_3_10.sh
sbatch ./exps/LassoLars_3_15.sh
sbatch ./exps/LassoLars_5_5.sh
sbatch ./exps/LassoLars_5_10.sh
sbatch ./exps/LassoLars_5_15.sh
sbatch ./exps/LassoLars_7_5.sh
sbatch ./exps/LassoLars_7_10.sh
sbatch ./exps/LassoLars_7_15.sh
sbatch ./exps/GaussianProcessRegressor_3_5.sh
sbatch ./exps/GaussianProcessRegressor_3_10.sh
sbatch ./exps/GaussianProcessRegressor_3_15.sh
sbatch ./exps/GaussianProcessRegressor_5_5.sh
sbatch ./exps/GaussianProcessRegressor_5_10.sh
sbatch ./exps/GaussianProcessRegressor_5_15.sh
sbatch ./exps/GaussianProcessRegressor_7_5.sh
sbatch ./exps/GaussianProcessRegressor_7_10.sh
sbatch ./exps/GaussianProcessRegressor_7_15.sh
sbatch ./exps/KNeighborsRegressor_3_5.sh
sbatch ./exps/KNeighborsRegressor_3_10.sh
sbatch ./exps/KNeighborsRegressor_3_15.sh
sbatch ./exps/KNeighborsRegressor_5_5.sh
sbatch ./exps/KNeighborsRegressor_5_10.sh
sbatch ./exps/KNeighborsRegressor_5_15.sh
sbatch ./exps/KNeighborsRegressor_7_5.sh
sbatch ./exps/KNeighborsRegressor_7_10.sh
sbatch ./exps/KNeighborsRegressor_7_15.sh
sbatch ./exps/RandomForestRegressor_3_5.sh
sbatch ./exps/RandomForestRegressor_3_10.sh
sbatch ./exps/RandomForestRegressor_3_15.sh
sbatch ./exps/RandomForestRegressor_5_5.sh
sbatch ./exps/RandomForestRegressor_5_10.sh
sbatch ./exps/RandomForestRegressor_5_15.sh
sbatch ./exps/RandomForestRegressor_7_5.sh
sbatch ./exps/RandomForestRegressor_7_10.sh
sbatch ./exps/RandomForestRegressor_7_15.sh
