#!/bin/bash
sbatch ./exps/LinearRegression_3_5.sh
sbatch ./exps/LinearRegression_3_10.sh
sbatch ./exps/LinearRegression_3_15.sh
sbatch ./exps/LinearRegression_5_5.sh
sbatch ./exps/LinearRegression_5_10.sh
sbatch ./exps/LinearRegression_5_15.sh
sbatch ./exps/LinearRegression_7_5.sh
sbatch ./exps/LinearRegression_7_10.sh
sbatch ./exps/LinearRegression_7_15.sh
sbatch ./exps/Ridge_3_5.sh
sbatch ./exps/Ridge_3_10.sh
sbatch ./exps/Ridge_3_15.sh
sbatch ./exps/Ridge_5_5.sh
sbatch ./exps/Ridge_5_10.sh
sbatch ./exps/Ridge_5_15.sh
sbatch ./exps/Ridge_7_5.sh
sbatch ./exps/Ridge_7_10.sh
sbatch ./exps/Ridge_7_15.sh
sbatch ./exps/RidgeCV_3_5.sh
sbatch ./exps/RidgeCV_3_10.sh
sbatch ./exps/RidgeCV_3_15.sh
sbatch ./exps/RidgeCV_5_5.sh
sbatch ./exps/RidgeCV_5_10.sh
sbatch ./exps/RidgeCV_5_15.sh
sbatch ./exps/RidgeCV_7_5.sh
sbatch ./exps/RidgeCV_7_10.sh
sbatch ./exps/RidgeCV_7_15.sh
sbatch ./exps/ElasticNetCV_3_5.sh
sbatch ./exps/ElasticNetCV_3_10.sh
sbatch ./exps/ElasticNetCV_3_15.sh
sbatch ./exps/ElasticNetCV_5_5.sh
sbatch ./exps/ElasticNetCV_5_10.sh
sbatch ./exps/ElasticNetCV_5_15.sh
sbatch ./exps/ElasticNetCV_7_5.sh
sbatch ./exps/ElasticNetCV_7_10.sh
sbatch ./exps/ElasticNetCV_7_15.sh
sbatch ./exps/LarsCV_3_5.sh
sbatch ./exps/LarsCV_3_10.sh
sbatch ./exps/LarsCV_3_15.sh
sbatch ./exps/LarsCV_5_5.sh
sbatch ./exps/LarsCV_5_10.sh
sbatch ./exps/LarsCV_5_15.sh
sbatch ./exps/LarsCV_7_5.sh
sbatch ./exps/LarsCV_7_10.sh
sbatch ./exps/LarsCV_7_15.sh
sbatch ./exps/MultiTaskElasticNet_3_5.sh
sbatch ./exps/MultiTaskElasticNet_3_10.sh
sbatch ./exps/MultiTaskElasticNet_3_15.sh
sbatch ./exps/MultiTaskElasticNet_5_5.sh
sbatch ./exps/MultiTaskElasticNet_5_10.sh
sbatch ./exps/MultiTaskElasticNet_5_15.sh
sbatch ./exps/MultiTaskElasticNet_7_5.sh
sbatch ./exps/MultiTaskElasticNet_7_10.sh
sbatch ./exps/MultiTaskElasticNet_7_15.sh
sbatch ./exps/MultiTaskLasso_3_5.sh
sbatch ./exps/MultiTaskLasso_3_10.sh
sbatch ./exps/MultiTaskLasso_3_15.sh
sbatch ./exps/MultiTaskLasso_5_5.sh
sbatch ./exps/MultiTaskLasso_5_10.sh
sbatch ./exps/MultiTaskLasso_5_15.sh
sbatch ./exps/MultiTaskLasso_7_5.sh
sbatch ./exps/MultiTaskLasso_7_10.sh
sbatch ./exps/MultiTaskLasso_7_15.sh
