#!/bin/bash
sbatch ./exps/0RandomForestRegressor_3_10.sh
sbatch ./exps/0RandomForestRegressor_3_15.sh
sbatch ./exps/0RandomForestRegressor_3_5.sh
sbatch ./exps/0RandomForestRegressor_5_10.sh
sbatch ./exps/0RandomForestRegressor_5_15.sh
sbatch ./exps/0RandomForestRegressor_5_5.sh
sbatch ./exps/0RandomForestRegressor_7_10.sh
sbatch ./exps/0RandomForestRegressor_7_15.sh
sbatch ./exps/0RandomForestRegressor_7_5.sh
sbatch ./exps/1Ridge_3_10.sh
sbatch ./exps/1Ridge_3_15.sh
sbatch ./exps/1Ridge_3_5.sh
sbatch ./exps/1Ridge_5_10.sh
sbatch ./exps/1Ridge_5_15.sh
sbatch ./exps/1Ridge_5_5.sh
sbatch ./exps/1Ridge_7_10.sh
sbatch ./exps/1Ridge_7_15.sh
sbatch ./exps/1Ridge_7_5.sh
sbatch ./exps/2RidgeCV_3_10.sh
sbatch ./exps/2RidgeCV_3_15.sh
sbatch ./exps/2RidgeCV_3_5.sh
sbatch ./exps/2RidgeCV_5_10.sh
sbatch ./exps/2RidgeCV_5_15.sh
sbatch ./exps/2RidgeCV_5_5.sh
sbatch ./exps/2RidgeCV_7_10.sh
sbatch ./exps/2RidgeCV_7_15.sh
sbatch ./exps/2RidgeCV_7_5.sh
sbatch ./exps/3LinearRegression_3_10.sh
sbatch ./exps/3LinearRegression_3_15.sh
sbatch ./exps/3LinearRegression_3_5.sh
sbatch ./exps/3LinearRegression_5_10.sh
sbatch ./exps/3LinearRegression_5_15.sh
sbatch ./exps/3LinearRegression_5_5.sh
sbatch ./exps/3LinearRegression_7_10.sh
sbatch ./exps/3LinearRegression_7_15.sh
sbatch ./exps/3LinearRegression_7_5.sh
sbatch ./exps/4ElasticNet_3_10.sh
sbatch ./exps/4ElasticNet_3_15.sh
sbatch ./exps/4ElasticNet_3_5.sh
sbatch ./exps/4ElasticNet_5_10.sh
sbatch ./exps/4ElasticNet_5_15.sh
sbatch ./exps/4ElasticNet_5_5.sh
sbatch ./exps/4ElasticNet_7_10.sh
sbatch ./exps/4ElasticNet_7_15.sh
sbatch ./exps/4ElasticNet_7_5.sh
sbatch ./exps/5ElasticNetCV_3_10.sh
sbatch ./exps/5ElasticNetCV_3_15.sh
sbatch ./exps/5ElasticNetCV_3_5.sh
sbatch ./exps/5ElasticNetCV_5_10.sh
sbatch ./exps/5ElasticNetCV_5_15.sh
sbatch ./exps/5ElasticNetCV_5_5.sh
sbatch ./exps/5ElasticNetCV_7_10.sh
sbatch ./exps/5ElasticNetCV_7_15.sh
sbatch ./exps/5ElasticNetCV_7_5.sh
sbatch ./exps/6MultiTaskElasticNet_3_10.sh
sbatch ./exps/6MultiTaskElasticNet_3_15.sh
sbatch ./exps/6MultiTaskElasticNet_3_5.sh
sbatch ./exps/6MultiTaskElasticNet_5_10.sh
sbatch ./exps/6MultiTaskElasticNet_5_15.sh
sbatch ./exps/6MultiTaskElasticNet_5_5.sh
sbatch ./exps/6MultiTaskElasticNet_7_10.sh
sbatch ./exps/6MultiTaskElasticNet_7_15.sh
sbatch ./exps/6MultiTaskElasticNet_7_5.sh
sbatch ./exps/7GaussianProcessRegressor_3_10.sh
sbatch ./exps/7GaussianProcessRegressor_3_15.sh
sbatch ./exps/7GaussianProcessRegressor_3_5.sh
sbatch ./exps/7GaussianProcessRegressor_5_10.sh
sbatch ./exps/7GaussianProcessRegressor_5_15.sh
sbatch ./exps/7GaussianProcessRegressor_5_5.sh
sbatch ./exps/7GaussianProcessRegressor_7_10.sh
sbatch ./exps/7GaussianProcessRegressor_7_15.sh
sbatch ./exps/7GaussianProcessRegressor_7_5.sh
sbatch ./exps/KNeighborsRegressor_3_10.sh
sbatch ./exps/KNeighborsRegressor_3_15.sh
sbatch ./exps/KNeighborsRegressor_3_5.sh
sbatch ./exps/KNeighborsRegressor_5_10.sh
sbatch ./exps/KNeighborsRegressor_5_15.sh
sbatch ./exps/KNeighborsRegressor_5_5.sh
sbatch ./exps/KNeighborsRegressor_7_10.sh
sbatch ./exps/KNeighborsRegressor_7_15.sh
sbatch ./exps/KNeighborsRegressor_7_5.sh
sbatch ./exps/Lasso_3_10.sh
sbatch ./exps/Lasso_3_15.sh
sbatch ./exps/Lasso_3_5.sh
sbatch ./exps/Lasso_5_10.sh
sbatch ./exps/Lasso_5_15.sh
sbatch ./exps/Lasso_5_5.sh
sbatch ./exps/Lasso_7_10.sh
sbatch ./exps/Lasso_7_15.sh
sbatch ./exps/Lasso_7_5.sh
sbatch ./exps/MultiTaskLasso_3_10.sh
sbatch ./exps/MultiTaskLasso_3_15.sh
sbatch ./exps/MultiTaskLasso_3_5.sh
sbatch ./exps/MultiTaskLasso_5_10.sh
sbatch ./exps/MultiTaskLasso_5_15.sh
sbatch ./exps/MultiTaskLasso_5_5.sh
sbatch ./exps/MultiTaskLasso_7_10.sh
sbatch ./exps/MultiTaskLasso_7_15.sh
sbatch ./exps/MultiTaskLasso_7_5.sh
