#!/bin/bash
sbatch /work/syseng/users/fjacevedo/Markovian/exps/ElasticNet_3_5.sh
sbatch /work/syseng/users/fjacevedo/Markovian/exps/ElasticNet_3_10.sh
sbatch /work/syseng/users/fjacevedo/Markovian/exps/ElasticNet_3_15.sh
sbatch /work/syseng/users/fjacevedo/Markovian/exps/ElasticNet_5_5.sh
sbatch /work/syseng/users/fjacevedo/Markovian/exps/ElasticNet_5_10.sh
sbatch /work/syseng/users/fjacevedo/Markovian/exps/ElasticNet_5_15.sh
sbatch /work/syseng/users/fjacevedo/Markovian/exps/ElasticNet_7_5.sh
sbatch /work/syseng/users/fjacevedo/Markovian/exps/ElasticNet_7_10.sh
sbatch /work/syseng/users/fjacevedo/Markovian/exps/ElasticNet_7_15.sh
sbatch /work/syseng/users/fjacevedo/Markovian/exps/Lars_3_5.sh
sbatch /work/syseng/users/fjacevedo/Markovian/exps/Lars_3_10.sh
sbatch /work/syseng/users/fjacevedo/Markovian/exps/Lars_3_15.sh
sbatch /work/syseng/users/fjacevedo/Markovian/exps/Lars_5_5.sh
sbatch /work/syseng/users/fjacevedo/Markovian/exps/Lars_5_10.sh
sbatch /work/syseng/users/fjacevedo/Markovian/exps/Lars_5_15.sh
sbatch /work/syseng/users/fjacevedo/Markovian/exps/Lars_7_5.sh
sbatch /work/syseng/users/fjacevedo/Markovian/exps/Lars_7_10.sh
sbatch /work/syseng/users/fjacevedo/Markovian/exps/Lars_7_15.sh
sbatch /work/syseng/users/fjacevedo/Markovian/exps/Lasso_3_5.sh
sbatch /work/syseng/users/fjacevedo/Markovian/exps/Lasso_3_10.sh
sbatch /work/syseng/users/fjacevedo/Markovian/exps/Lasso_3_15.sh
sbatch /work/syseng/users/fjacevedo/Markovian/exps/Lasso_5_5.sh
sbatch /work/syseng/users/fjacevedo/Markovian/exps/Lasso_5_10.sh
sbatch /work/syseng/users/fjacevedo/Markovian/exps/Lasso_5_15.sh
sbatch /work/syseng/users/fjacevedo/Markovian/exps/Lasso_7_5.sh
sbatch /work/syseng/users/fjacevedo/Markovian/exps/Lasso_7_10.sh
sbatch /work/syseng/users/fjacevedo/Markovian/exps/Lasso_7_15.sh
sbatch /work/syseng/users/fjacevedo/Markovian/exps/LassoLars_3_5.sh
sbatch /work/syseng/users/fjacevedo/Markovian/exps/LassoLars_3_10.sh
sbatch /work/syseng/users/fjacevedo/Markovian/exps/LassoLars_3_15.sh
sbatch /work/syseng/users/fjacevedo/Markovian/exps/LassoLars_5_5.sh
sbatch /work/syseng/users/fjacevedo/Markovian/exps/LassoLars_5_10.sh
sbatch /work/syseng/users/fjacevedo/Markovian/exps/LassoLars_5_15.sh
sbatch /work/syseng/users/fjacevedo/Markovian/exps/LassoLars_7_5.sh
sbatch /work/syseng/users/fjacevedo/Markovian/exps/LassoLars_7_10.sh
sbatch /work/syseng/users/fjacevedo/Markovian/exps/LassoLars_7_15.sh
sbatch /work/syseng/users/fjacevedo/Markovian/exps/ARDRegression_3_5.sh
sbatch /work/syseng/users/fjacevedo/Markovian/exps/ARDRegression_3_10.sh
sbatch /work/syseng/users/fjacevedo/Markovian/exps/ARDRegression_3_15.sh
sbatch /work/syseng/users/fjacevedo/Markovian/exps/ARDRegression_5_5.sh
sbatch /work/syseng/users/fjacevedo/Markovian/exps/ARDRegression_5_10.sh
sbatch /work/syseng/users/fjacevedo/Markovian/exps/ARDRegression_5_15.sh
sbatch /work/syseng/users/fjacevedo/Markovian/exps/ARDRegression_7_5.sh
sbatch /work/syseng/users/fjacevedo/Markovian/exps/ARDRegression_7_10.sh
sbatch /work/syseng/users/fjacevedo/Markovian/exps/ARDRegression_7_15.sh
sbatch /work/syseng/users/fjacevedo/Markovian/exps/BayesianRidge_3_5.sh
sbatch /work/syseng/users/fjacevedo/Markovian/exps/BayesianRidge_3_10.sh
sbatch /work/syseng/users/fjacevedo/Markovian/exps/BayesianRidge_3_15.sh
sbatch /work/syseng/users/fjacevedo/Markovian/exps/BayesianRidge_5_5.sh
sbatch /work/syseng/users/fjacevedo/Markovian/exps/BayesianRidge_5_10.sh
sbatch /work/syseng/users/fjacevedo/Markovian/exps/BayesianRidge_5_15.sh
sbatch /work/syseng/users/fjacevedo/Markovian/exps/BayesianRidge_7_5.sh
sbatch /work/syseng/users/fjacevedo/Markovian/exps/BayesianRidge_7_10.sh
sbatch /work/syseng/users/fjacevedo/Markovian/exps/BayesianRidge_7_15.sh
sbatch /work/syseng/users/fjacevedo/Markovian/exps/GaussianProcessRegressor_3_5.sh
sbatch /work/syseng/users/fjacevedo/Markovian/exps/GaussianProcessRegressor_3_10.sh
sbatch /work/syseng/users/fjacevedo/Markovian/exps/GaussianProcessRegressor_3_15.sh
sbatch /work/syseng/users/fjacevedo/Markovian/exps/GaussianProcessRegressor_5_5.sh
sbatch /work/syseng/users/fjacevedo/Markovian/exps/GaussianProcessRegressor_5_10.sh
sbatch /work/syseng/users/fjacevedo/Markovian/exps/GaussianProcessRegressor_5_15.sh
sbatch /work/syseng/users/fjacevedo/Markovian/exps/GaussianProcessRegressor_7_5.sh
sbatch /work/syseng/users/fjacevedo/Markovian/exps/GaussianProcessRegressor_7_10.sh
sbatch /work/syseng/users/fjacevedo/Markovian/exps/GaussianProcessRegressor_7_15.sh
sbatch /work/syseng/users/fjacevedo/Markovian/exps/AdaBoostRegressor_3_5.sh
sbatch /work/syseng/users/fjacevedo/Markovian/exps/AdaBoostRegressor_3_10.sh
sbatch /work/syseng/users/fjacevedo/Markovian/exps/AdaBoostRegressor_3_15.sh
sbatch /work/syseng/users/fjacevedo/Markovian/exps/AdaBoostRegressor_5_5.sh
sbatch /work/syseng/users/fjacevedo/Markovian/exps/AdaBoostRegressor_5_10.sh
sbatch /work/syseng/users/fjacevedo/Markovian/exps/AdaBoostRegressor_5_15.sh
sbatch /work/syseng/users/fjacevedo/Markovian/exps/AdaBoostRegressor_7_5.sh
sbatch /work/syseng/users/fjacevedo/Markovian/exps/AdaBoostRegressor_7_10.sh
sbatch /work/syseng/users/fjacevedo/Markovian/exps/AdaBoostRegressor_7_15.sh
sbatch /work/syseng/users/fjacevedo/Markovian/exps/KNeighborsRegressor_3_5.sh
sbatch /work/syseng/users/fjacevedo/Markovian/exps/KNeighborsRegressor_3_10.sh
sbatch /work/syseng/users/fjacevedo/Markovian/exps/KNeighborsRegressor_3_15.sh
sbatch /work/syseng/users/fjacevedo/Markovian/exps/KNeighborsRegressor_5_5.sh
sbatch /work/syseng/users/fjacevedo/Markovian/exps/KNeighborsRegressor_5_10.sh
sbatch /work/syseng/users/fjacevedo/Markovian/exps/KNeighborsRegressor_5_15.sh
sbatch /work/syseng/users/fjacevedo/Markovian/exps/KNeighborsRegressor_7_5.sh
sbatch /work/syseng/users/fjacevedo/Markovian/exps/KNeighborsRegressor_7_10.sh
sbatch /work/syseng/users/fjacevedo/Markovian/exps/KNeighborsRegressor_7_15.sh
sbatch /work/syseng/users/fjacevedo/Markovian/exps/RandomForestRegressor_3_5.sh
sbatch /work/syseng/users/fjacevedo/Markovian/exps/RandomForestRegressor_3_10.sh
sbatch /work/syseng/users/fjacevedo/Markovian/exps/RandomForestRegressor_3_15.sh
sbatch /work/syseng/users/fjacevedo/Markovian/exps/RandomForestRegressor_5_5.sh
sbatch /work/syseng/users/fjacevedo/Markovian/exps/RandomForestRegressor_5_10.sh
sbatch /work/syseng/users/fjacevedo/Markovian/exps/RandomForestRegressor_5_15.sh
sbatch /work/syseng/users/fjacevedo/Markovian/exps/RandomForestRegressor_7_5.sh
sbatch /work/syseng/users/fjacevedo/Markovian/exps/RandomForestRegressor_7_10.sh
sbatch /work/syseng/users/fjacevedo/Markovian/exps/RandomForestRegressor_7_15.sh
sbatch /work/syseng/users/fjacevedo/Markovian/exps/HistGradientBoostingRegressor_3_5.sh
sbatch /work/syseng/users/fjacevedo/Markovian/exps/HistGradientBoostingRegressor_3_10.sh
sbatch /work/syseng/users/fjacevedo/Markovian/exps/HistGradientBoostingRegressor_3_15.sh
sbatch /work/syseng/users/fjacevedo/Markovian/exps/HistGradientBoostingRegressor_5_5.sh
sbatch /work/syseng/users/fjacevedo/Markovian/exps/HistGradientBoostingRegressor_5_10.sh
sbatch /work/syseng/users/fjacevedo/Markovian/exps/HistGradientBoostingRegressor_5_15.sh
sbatch /work/syseng/users/fjacevedo/Markovian/exps/HistGradientBoostingRegressor_7_5.sh
sbatch /work/syseng/users/fjacevedo/Markovian/exps/HistGradientBoostingRegressor_7_10.sh
sbatch /work/syseng/users/fjacevedo/Markovian/exps/HistGradientBoostingRegressor_7_15.sh
sbatch /work/syseng/users/fjacevedo/Markovian/exps/GradientBoostingRegressor_3_5.sh
sbatch /work/syseng/users/fjacevedo/Markovian/exps/GradientBoostingRegressor_3_10.sh
sbatch /work/syseng/users/fjacevedo/Markovian/exps/GradientBoostingRegressor_3_15.sh
sbatch /work/syseng/users/fjacevedo/Markovian/exps/GradientBoostingRegressor_5_5.sh
sbatch /work/syseng/users/fjacevedo/Markovian/exps/GradientBoostingRegressor_5_10.sh
sbatch /work/syseng/users/fjacevedo/Markovian/exps/GradientBoostingRegressor_5_15.sh
sbatch /work/syseng/users/fjacevedo/Markovian/exps/GradientBoostingRegressor_7_5.sh
sbatch /work/syseng/users/fjacevedo/Markovian/exps/GradientBoostingRegressor_7_10.sh
sbatch /work/syseng/users/fjacevedo/Markovian/exps/GradientBoostingRegressor_7_15.sh
